### PR TITLE
Fixed compiler warnings due to format string types.

### PR DESCRIPTION
**Pull request by quellish**
Updated format strings due to compiler warnings.

### CODE REVIEW

**Comment by twobitlabs** [comment]
@quellish thanks for the PR!

@chrispix this PR also includes os_trace calls which are iOS 8+ only. What do you think?

**Comment by quellish** [comment]
Unfortunately I merged a fork before I submitted the PR, which is why both sets of changes are in this PR.

I saw that the deployment target is now 8.4, which would cover use of activity tracing. I can add a runtime check for the activity tracing methods if you would be more comfortable with that.

As far as os_trace_with_payload, that is MacOS only and a little more involved to implement. I can do that in another PR but it may not be worthwhile.

**Comment by twobitlabs** [comment]
@thuss I'm fine with making AnalyticsKit iOS 8+. @quellish would you mind adding `os_trace` calls to the `logEvent` methods as well?

**Comment by quellish** [comment]
Will do

**Comment by quellish** [comment]
Added activity tracing to the logEvent methods. Activity tracing doesn't allow us to pass anything but scalar values, so the event string and payload do not get passed to activity tracing - but the "breadcrumbs" of the os_trace calls should help with troubleshooting any production issues.

**Comment by twobitlabs** [comment]
looks good, thanks for tackling this!

**Pull request merged**
