### PR TITLE
Compatibility changes for Adjust 4.2.7.

### PR DESCRIPTION
**Pull request by seanw4**

### CODE REVIEW

**Comment by twobitlabs** [comment]
We just fixed some broken tests related to the crashlytics library. Can you merge master into this branch and push again?

**Comment by twobitlabs** [comment]
Sean, feel free to add your name to the bottom of the README.md file is you like!

**Comment by seanw4** [comment]
Thanks - Just added my name. I think I have that latest commit already. Are you referring to this one:

https://github.com/seanw4/AnalyticsKit/commit/a8d9fbb2c2436c32a319e1a4bbcfdd48eb615a3a

**Comment by twobitlabs** [comment]
Looks like it's passing. Accepting the PR.

**Pull request merged**
