### PR TITLE
fix mixpanel provider implementation

### PR DESCRIPTION
**Pull request by brightredchilli**
Mixpanel provider doesn't call the 'timeEvent' method on the mixpanel library properly.

### CODE REVIEW

**Comment by twobitlabs** [comment]
Looks like the unit tests are failing on compiling this updated MixPanelProvider:

https://travis-ci.org/twobitlabs/AnalyticsKit/builds/103679277

maybe the version of MixPanel in AnalyticsKit needs to be updated?

**Comment by brightredchilli** [comment]
@twobitlabs sorry for the late response! Yes indeed, it looks like the mixpanel version that the test is running against is old. The issue here though, I think is that travis does not run pod install before running tests...If it did, it should have pulled down the latest version of mixpanel.

**Comment by twobitlabs** [comment]
Would you mind updating the MixPanel SDK included in the project? While we offer cocoapods as an option for analyticskit it's not required so for the tests we rely on the version in the repository.

**Comment by brightredchilli** [comment]
oh well, that didn't work : ) i diidnt look carefully. looks like ill have to update the files in the project itself. ill do that tomorrow.

**Comment by twobitlabs** [comment]
@brightredchilli it looks like you need to link the `libicucore` library in the test target

**Comment by twobitlabs** [comment]
Also feel free to add yourself to the contributors at the bottom of https://github.com/twobitlabs/AnalyticsKit/blob/master/README.md

**Comment by brightredchilli** [comment]
yknow, im struggling a little here - i did include it. for some reason this is not picking up. The SHA of my commit also does not match.

**Comment by brightredchilli** [comment]
I think this is a travis shenanigan...I'll try adding another commit..

**Comment by twobitlabs** [comment]
yeah the tests are passing for me locally too, not sure what's up with Travis. Going to merge this. Thanks!

**Comment by brightredchilli** [comment]
it keeps checking out old SHAs. the SHA of the failing test does not match my latest commit. I have a feeling it is confused when I rebase. It's a bummer. Yup. Would you also be able to submit a new version to cocoapods? I can help with that if necessary

**Comment by twobitlabs** [comment]
are there any changes required to the podspec, or do you just need a version bump?

**Comment by brightredchilli** [comment]
I think we probably should require the version where mixpanel 'timeEvent' call was introduced. i can update the podspec but i need a couple of hours, afk right now.

**Comment by twobitlabs** [comment]
Honestly, I'm thinking about dumping Cocoapods altogether. I haven't been able to push an update for a while because pod spec lint fails. Most of the dependencies fail with `The 'Pods' target has transitive dependencies that include static binaries`.

I've spent more time than I care to try to get the pod lint to pass, and I don't really want to invest more time, as we don't use Cocoapods ourselves, and AnalyticsKit is trivial to integrate without it.

**Pull request merged**
