### PR TITLE
Mark initializers in AnalyticsKitChannel with public access

### PR DESCRIPTION
**Pull request by jjamminjim**
Also bumped the podspec version.

### CODE REVIEW

**Comment by twobitlabs** [comment]
Thanks Jim!

**Comment by jjamminjim** [comment]
@twobitlabs : My pleasure. Any idea when you might post the swift version to cocoapods?

**Comment by twobitlabs** [comment]
@jjamminjim we don't use cocoapods or officially support it. I tried publishing the update, but I'm not sure I know how. `pod trunk push` results in:

```
Validating podspec
 -> AnalyticsKit (2.1.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/5y/7qbcynwj66d59ktvx1v9bl300000gn/T/CocoaPods/Lint/Pods/Crashlytics/iOS/Crashlytics.framework, /private/var/folders/5y/7qbcynwj66d59ktvx1v9bl300000gn/T/CocoaPods/Lint/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a, /private/var/folders/5y/7qbcynwj66d59ktvx1v9bl300000gn/T/CocoaPods/Lint/Pods/Intercom/Intercom/Intercom.framework, and /private/var/folders/5y/7qbcynwj66d59ktvx1v9bl300000gn/T/CocoaPods/Lint/Pods/NewRelicAgent/NewRelicAgent/NewRelicAgent.framework)) during validation.

[!] The spec did not pass validation, due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run:
    `echo "2.3" > .swift-version`.
```

**Comment by jjamminjim** [comment]
@twobitlabs : Yea, that is a problem. It revolves around the providers that are dependent on third-party static-libraries (crashlytics, intercom, googleanalytics, etc.). You probably know all of this but, dynamic libraries can not link against static-libraries, so AnalyticsKit can not be dependent on (link against) these static-library pods. 

 My solution is to simply import the `AnalyticsKit/Core` sub-spec and directly compile the offending AK-provider's source into my apps.   Additionally I have to import the supporting pods via my Podfile.  This way the static-libraries link directly into my app, with no AK dependencies.

I think you could submit an update to cocoapods successfully if you removed the provider sub-specs that are dependent on these static libraries. You'll have to document an alternative usage-pattern for these, but people are being forced to do that anyway. I can help if you'd like

**Comment by twobitlabs** [comment]
I tried just commenting those subspecs on the release branch, but then it runs into a bunch of other problems. If you want to take a whack at it, I can add you as an owner of the pod. Let me know.

**Comment by jjamminjim** [comment]
@twobitlabs : Yes, if you want to give me access, I'll take a crack at it.

**Comment by twobitlabs** [comment]
Looks like I need your email address to add you. Can you send it to cpickslay at twobitlabs?

**Pull request merged**
